version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: app
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local